apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/srv/app-data"
